#!/bin/sh -ex

USER=node
adduser --system --group --shell /bin/bash $USER

cat>/etc/systemd/system/pm2-$USER.service<<EOF
[Unit]
Description=PM2 next gen process manager for Node.js
After=network.target remote-fs.target

[Service]
Type=forking
User=$USER

LimitNOFILE=infinity

ExecStart=/usr/local/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/local/lib/node_modules/pm2/bin/pm2 reload all

ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 dump
ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 delete all
ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target
EOF

PM2_PATH=/home/$USER/.pm2/
mkdir -p $PM2_PATH
echo '[]' > $PM2_PATH/dump.pm2

PM2_LOG=/var/log/pm2-$USER
mkdir -p $PM2_LOG
ln -s $PM2_LOG $PM2_PATH/logs
ln -s $PM2_LOG/pm2.log $PM2_PATH/pm2.log

chown -R $USER:$USER $PM2_PATH $PM2_LOG

systemctl enable pm2-$USER

