#!/bin/sh -ex

NODEAPP=/opt/tklweb-cp

# setup tklweb-cp
mkdir -p $NODEAPP/public/javascripts
mkdir -p $NODEAPP/public/stylesheets
mkdir -p $NODEAPP/public/images
mv /var/www/js/* $NODEAPP/public/javascripts/
mv /var/www/css/* $NODEAPP/public/stylesheets/
mv /var/www/images/* $NODEAPP/public/images/
rm -rf /var/www/{js,css,images}

chown -R node:node $NODEAPP

# install deps
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
cd $NODEAPP
su $NODEAPP_USER -c "npm install"
unset HTTP_PROXY

su node -c "pm2 start tklweb-cp.js; pm2 dump; pm2 kill"
