#!/bin/bash -ex

#npm install -g pm2
#npm install -g forever

USER=node
PM2_BIN=/usr/local/lib/node_modules/pm2/bin/pm2
PM2_PATH=/home/$USER/.pm2/
PM2_LOG=/var/log/pm2-$USER

mkdir -p $PM2_PATH

mkdir -p $PM2_LOG
ln -s $PM2_LOG $PM2_PATH/logs

chown -R $USER:$USER $PM2_PATH $PM2_LOG

update-rc.d pm2 defaults

