#!/bin/bash -ex

EXAMPLES=/opt/node-examples

# install examples
mkdir -p $EXAMPLES
cd $EXAMPLES

for i in Hendrik/node-by-example shapeshed/express_example shapeshed/nodejsbook.io.examples azat-co/practicalnode; do
    git clone "https://github.com/$i.git"
done

cd practicalnode
rm -rf .git
find -type d -name node_modules -exec rm -rf \{} \+

chown -R $USER:$USER $EXAMPLES

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/nodejs /etc/nginx/sites-enabled/nodejs

rm -rf /tmp/npm*
